build error

diff --git a/.github/workflows/server-build.yml b/.github/workflows/server-build.yml
--- a/.github/workflows/server-build.yml
+++ b/.github/workflows/server-build.yml
@@ -183,96 +183,96 @@ jobs:
         run: |
           ./build.sh -DskipTests
 
-          - name: Run only tests
-          if: (inputs.skip-tests != 'true' || steps.run_result.outputs.run_result == 'failedtest') && (steps.changed-files-specific.outputs.any_changed == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
-          env:
-            ACTIVE_PROFILE: test
-            APPSMITH_CLOUD_SERVICES_BASE_URL: "https://release-cs.appsmith.com"
-            APPSMITH_CLOUD_SERVICES_TEMPLATE_UPLOAD_AUTH: ${{ secrets.APPSMITH_CLOUD_SERVICES_TEMPLATE_UPLOAD_AUTH }}
-            APPSMITH_REDIS_URL: "redis://127.0.0.1:6379"
-            APPSMITH_ENCRYPTION_PASSWORD: "password"
-            APPSMITH_ENCRYPTION_SALT: "salt"
-            APPSMITH_ENVFILE_PATH: /tmp/dummy.env
-            APPSMITH_VERBOSE_LOGGING_ENABLED: false
-          run: |
-            if [[ "${{ inputs.is-pg-build }}" == "true" ]]; then
-              export APPSMITH_DB_URL="postgresql://postgres:password@localhost:5432/postgres"
-            else
-              export APPSMITH_DB_URL="mongodb://localhost:27017/mobtools"
-            fi
-  
-            args=()
-  
-            # Check if it's a failed test re-run
-            if [[ "${{ steps.run_result.outputs.run_result }}" == "failedtest" ]]; then
-              failed_tests="${{ steps.failed_tests.outputs.tests }}"
-              args+=("-DfailIfNoTests=false" "-Dsurefire.failIfNoSpecifiedTests=false" "-Dtest=${failed_tests}")
-            fi
-  
-            # Run the tests and capture the output while printing to console
-            echo "Running tests..."
-            output=$(mvn test "${args[@]}" 2>&1) # Capture output to variable
-            echo "$output" # Print output to console
-  
-            # Initialize arrays to store failed and skipped module names
-            failed_modules=()
-            skipped_modules=()
-  
-            # Process the captured output
-            while IFS= read -r line; do
-                if [[ $line == *"FAILURE"* ]]; then
-                    module_name=$(echo "$line" | awk '{print $1}')
-                    failed_modules+=("$module_name")
-                elif [[ $line == *"SKIPPED"* ]]; then
-                    module_name=$(echo "$line" | awk '{print $1}')
-                    skipped_modules+=("$module_name")
-                fi
-            done <<< "$output"
-  
-            # Combine failed and skipped modules into one list for searching
-            all_modules=("${failed_modules[@]}" "${skipped_modules[@]}")
-            OUTPUT_FILE="failed_skipped_tests.txt"
-            > "$OUTPUT_FILE"
-  
-            # Search for test classes corresponding to the modules
-            for module in "${all_modules[@]}"; do
-                test_classes=$(find . -type f -name "*${module}*.java" | sed 's|.*/||; s|\.java$||; s|^|com.external.plugins.|')
-                for class in $test_classes; do
-                    echo "${class}#" >> "$OUTPUT_FILE"
-                done
-            done
-  
-            echo "List of failed and skipped test cases generated in $OUTPUT_FILE:"
-            cat "$OUTPUT_FILE"
-  
-            # Check if any tests failed and create a failed tests list
-            if [[ ${#failed_modules[@]} -gt 0 ]]; then
-                failed_tests_file="$PWD/failed-server-tests.txt"
-                gawk -F\" '/<testcase / {cur_test = $4 "#" $2} /<(failure|error) / {print cur_test}' $(find . -type f -name 'TEST-*.xml') \
-                    | sort -u \
-                    | tee "$failed_tests_file"
-                echo "Saved to $failed_tests_file"
-  
-                # Check if there are any tests to report
-                if [[ -s $failed_tests_file ]]; then
-                    content="$(
-                        echo "## Failed Server Tests"
-                        echo
-                        sed 's/^/- /' "$failed_tests_file"
-                    )"
-                    echo "$content" >> "$GITHUB_STEP_SUMMARY"
-                    # Add a comment to the PR with the list of failed tests
-                    curl --silent --show-error \
-                        --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-                        --data "$(jq -n --arg body "$content" '$ARGS.named')" \
-                        "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/${{ inputs.pr }}/comments" \
-                        > /dev/null
-                fi
-  
-                # Exit with an error code if there are failed tests
-                exit 1
-            fi
-            
+      # Run only tests
+      - name: Run only tests
+        if: (inputs.skip-tests != 'true' || steps.run_result.outputs.run_result == 'failedtest') && (steps.changed-files-specific.outputs.any_changed == 'true' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
+        env:
+          ACTIVE_PROFILE: test
+          APPSMITH_CLOUD_SERVICES_BASE_URL: "https://release-cs.appsmith.com"
+          APPSMITH_CLOUD_SERVICES_TEMPLATE_UPLOAD_AUTH: ${{ secrets.APPSMITH_CLOUD_SERVICES_TEMPLATE_UPLOAD_AUTH }}
+          APPSMITH_REDIS_URL: "redis://127.0.0.1:6379"
+          APPSMITH_ENCRYPTION_PASSWORD: "password"
+          APPSMITH_ENCRYPTION_SALT: "salt"
+          APPSMITH_ENVFILE_PATH: /tmp/dummy.env
+          APPSMITH_VERBOSE_LOGGING_ENABLED: false
+        run: |
+          if [[ "${{ inputs.is-pg-build }}" == "true" ]]; then
+            export APPSMITH_DB_URL="postgresql://postgres:password@localhost:5432/postgres"
+          else
+            export APPSMITH_DB_URL="mongodb://localhost:27017/mobtools"
+          fi
+
+          args=()
+
+          # Check if it's a failed test re-run
+          if [[ "${{ steps.run_result.outputs.run_result }}" == "failedtest" ]]; then
+            failed_tests="${{ steps.failed_tests.outputs.tests }}"
+            args+=("-DfailIfNoTests=false" "-Dsurefire.failIfNoSpecifiedTests=false" "-Dtest=${failed_tests}")
+          fi
+
+          # Run the tests and capture the output while printing to console
+          echo "Running tests..."
+          output=$(mvn test "${args[@]}" 2>&1) # Capture output to variable
+          echo "$output" # Print output to console
+
+          # Initialize arrays to store failed and skipped module names
+          failed_modules=()
+          skipped_modules=()
+
+          # Process the captured output
+          while IFS= read -r line; do
+              if [[ $line == *"FAILURE"* ]]; then
+                  module_name=$(echo "$line" | awk '{print $1}')
+                  failed_modules+=("$module_name")
+              elif [[ $line == *"SKIPPED"* ]]; then
+                  module_name=$(echo "$line" | awk '{print $1}')
+                  skipped_modules+=("$module_name")
+              fi
+          done <<< "$output"
+
+          # Combine failed and skipped modules into one list for searching
+          all_modules=("${failed_modules[@]}" "${skipped_modules[@]}")
+          OUTPUT_FILE="failed_skipped_tests.txt"
+          > "$OUTPUT_FILE"
+
+          # Search for test classes corresponding to the modules
+          for module in "${all_modules[@]}"; do
+              test_classes=$(find . -type f -name "*${module}*.java" | sed 's|.*/||; s|\.java$||; s|^|com.external.plugins.|')
+              for class in $test_classes; do
+                  echo "${class}#" >> "$OUTPUT_FILE"
+              done
+          done
+
+          echo "List of failed and skipped test cases generated in $OUTPUT_FILE:"
+          cat "$OUTPUT_FILE"
+
+          # Check if any tests failed and create a failed tests list
+          if [[ ${#failed_modules[@]} -gt 0 ]]; then
+              failed_tests_file="$PWD/failed-server-tests.txt"
+              gawk -F\" '/<testcase / {cur_test = $4 "#" $2} /<(failure|error) / {print cur_test}' $(find . -type f -name 'TEST-*.xml') \
+                  | sort -u \
+                  | tee "$failed_tests_file"
+              echo "Saved to $failed_tests_file"
+
+              # Check if there are any tests to report
+              if [[ -s $failed_tests_file ]]; then
+                  content="$(
+                      echo "## Failed Server Tests"
+                      echo
+                      sed 's/^/- /' "$failed_tests_file"
+                  )"
+                  echo "$content" >> "$GITHUB_STEP_SUMMARY"
+                  # Add a comment to the PR with the list of failed tests
+                  curl --silent --show-error \
+                      --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+                      --data "$(jq -n --arg body "$content" '$ARGS.named')" \
+                      "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/${{ inputs.pr }}/comments" \
+                      > /dev/null
+              fi
+
+              # Exit with an error code if there are failed tests
+              exit 1
+          fi
       # # Step to find and move test report XML files to a folder
       # - name: Find and move test report XML files to a folder
       #   id: move_test_reports
